services:
  web:
    volumes:
      - ./app:/app
    command: flask run --host=0.0.0.0 --port=8087
    environment:
      - FLASK_ENV=development

  redis:
    volumes:
      - redis_data:/data

  nginx:
    ports:
      - "8081:8081"  # Dev NGINX

volumes:
  redis_data:

