version: '3'

services:
  web:
    build: .  # Build the Flask app from Dockerfile
    ports:
      - "8088:8088"  # Internal port for Flask in dev and prod
    depends_on:
      - redis  # Wait for Redis to be ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"]  # Check if Flask is alive
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - devnet  # Internal Docker network

  redis:
    image: redis:alpine  # Lightweight Redis image
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # Ensure Redis is responsive
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - devnet

  nginx:
    image: nginx:alpine  # Lightweight Nginx image
    ports:
      - "8081:8081"  # Use port 8081 externally for development instead of 80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx config
    depends_on:
      - web
    networks:
      - devnet

networks:
  devnet:
    driver: bridge  # Standard bridge network for communication

