
services:
  web:
    build: .
    ports:
      - "8087:8087"  # Dev default
    depends_on:
      - redis
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8087"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    networks:
      - devnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"  # Dev NGINX
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

