version: '3'

services:
  web:
    build: .
    ports:
      - "8088:8088"  # Prod Flask
    command: gunicorn app:app --bind 0.0.0.0:8088
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis
    networks:
      - devnet
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - devnet
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "8082:8082"  # Prod NGINX
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - devnet
    restart: always

networks:
  devnet:
    driver: bridge

volumes:
  redis_data:

