version: '3'

services:
  web:
    volumes:
      - ./app:/app  # Mount app source code for live development
    command: flask run --host=0.0.0.0 --port=8088 --reload  # Auto-reload Flask on code changes
    environment:
      - FLASK_ENV=development  # Flask development environment
    depends_on:
      - redis

  redis:
    volumes:
      - redis_data:/data  # Persistent Redis data storage

volumes:
  redis_data:  # Declare the volume for Redis data

